// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VertoTask.Data;

#nullable disable

namespace VertoTask.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250811133709_Final")]
    partial class Final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VertoTask.Models.GlobalContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdressName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoopyRightext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("HeaderLinks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionBoxPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermsConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteMakerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("interactionText1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("interactionText2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GlobalContents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdressLine1 = "The Crabtree, Quinton Green Park,",
                            AdressLine2 = "Quinton, Northampton, NN7 2EG",
                            AdressName = "Head Office",
                            ContactEmail = "hello@iotaofficefurniture.co.uk",
                            CoopyRightext = "© iOTA Interiors Limited T/A iOTA Office Furniture",
                            HeaderLinks = "[\"Home\",\"Services\",\"Sustainability\",\"Our work\",\"Resources\",\"About IOTA\",\"Contact us\"]",
                            LogoImagePath = "images/logo.png",
                            QuestionBoxPath = "images/Rectangle 121.png",
                            TermsConditions = "Terms and conditions",
                            WebsiteMakerText = "Site by Verto",
                            interactionText1 = "Connect with us",
                            interactionText2 = "Like us",
                            phoneNumber = "+44(0) 1604289630"
                        });
                });

            modelBuilder.Entity("VertoTask.Models.HomepageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Section1_Image1Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section1_TextOverCarousel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section2_ButtonText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section2_Image1Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section2_SubTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section2_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section3_FloatingText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section4_GlobalText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section4_Image1Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section4_Image1Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section4_Image1Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section4_Image2Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section4_Image3Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section5_Image1Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section5_Image2Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section5_SubTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section5_Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomepageContents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Section1_Image1Path = "images/image4.png",
                            Section1_TextOverCarousel = "Creating Exceptional Workspaces",
                            Section2_ButtonText = "WHAT WE DO",
                            Section2_Image1Path = "images/circle-icons.png",
                            Section2_SubTitle = "Specialists in transforming commercial spaces into agile, functional and empowering environments.",
                            Section2_Title = "Custom built design & furniture solutions",
                            Section3_FloatingText = "Explore our latest work...",
                            Section4_GlobalText = "VIEW MORE->",
                            Section4_Image1Description = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam.",
                            Section4_Image1Path = "images/image2.png",
                            Section4_Image1Title = "Case Study Name Here",
                            Section4_Image2Title = "Case Study Name Here",
                            Section4_Image3Title = "Case Study Name Here",
                            Section5_Image1Text = "WATCH THE VIDEO",
                            Section5_Image2Text = "ABOUT iOTA",
                            Section5_SubTitle = "Find out who we are, why we do it and why we love what we do.",
                            Section5_Title = "Discover more about iOTA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
